apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandeep-app
  name: sandeep-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandeep-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sandeep-app
    spec:
      containers:
        - image: >-
            gcr.io/my-test-project-02-284307/github.com/sandeep8308099903/test-web
          imagePullPolicy: IfNotPresent
          name: sandeep-app
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: sandeep-app
  name: sandeep-app-service
  namespace: default
spec:
  clusterIP: 10.40.15.177
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32201
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: sandeep-app
  sessionAffinity: None
  type: LoadBalancer

